# Generated by Django 5.0.6 on 2024-06-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_usuario_usuario_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
