# Generated by Django 5.0.6 on 2024-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
                ('apPaterno', models.CharField(max_length=20)),
                ('apMaterno', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=20)),
                ('confirmar_contraseña', models.CharField(max_length=20)),
                ('edad', models.IntegerField(max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id_usuario'],
            },
        ),
    ]
