# Generated by Django 4.1.2 on 2024-06-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_alter_usuario_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apPaterno',
            new_name='apellido',
        ),
    ]
